name: reciperecommender
dependencies:
  - catboost=1.2
  - pip=23.0.1
  - Flask=2.3.2
  - libclang=16.0.6
  - matplotlib=3.7.1
  - nltk=3.8.1
  - numpy=1.24.3
  - pandas=2.0.2
  - Pillow=9.5.0
  - plotly=5.14.1
  - pyarrow=12.0.1
  - PyYAML=6.0
  - regex=2023.6.3
  - scikit-learn=1.3.0
  - scipy=1.10.1
  - tokenizers=0.13.3
  - torchvision=0.15.2
  - transformers=4.30.2
  - pip:
    - huggingface-hub==0.15.1
    - torch==2.0.1
    - torchdata==0.6.1
    - torchtext==0.15.2
